### ISSUE TITLE
Entities in groups can't be cross-referenced

### ISSUE THREAD

**Issue by cjdb** [breathe-doc/breathe#921] opened 2023-05-20 16:42 UTC
Given
```cpp
/// \defgroup A
/// some desc
/// \{
void f();
void g();
/// \}

/// Calls :cpp:func:`f`.
void h();
```
and
```rst
.. doxygengroup:: A

.. doxygenfunction:: h
```

I should get a clickable link to `f` in `h`'s description: this isn't the case right now.

**Comment by vermeeren** [comment] 2023-05-23 11:43
@cjdb I think this is a duplicate of #912, see https://github.com/breathe-doc/breathe/issues/912#issuecomment-1531601209.

**Closed by vermeeren** 2023-05-23 11:43 UTC
Labels: duplicate, support
